import { Containers } from '@workspace/typescript-interface/docker/docker.containers';
import { Network } from '@workspace/typescript-interface/docker/docker.network';
export declare const BUILTIN_NETWORKS: readonly ['bridge', 'host', 'none'];
export declare function isBuiltinNetwork(name: string): boolean;
export declare const NEXPLOY_INFRASTRUCTURE_CONTAINERS: string[];
export declare const NEXPLOY_INFRASTRUCTURE_NETWORKS: string[];
export declare function isNexployInfrastructureContainer(container: Containers): boolean;
export declare function isNexployInfrastructureNetwork(network: Network): boolean;
export declare function isNexployInfrastructureNetworkName(networkName: string): boolean;
export declare function filterNexployContainers(containers: Containers[]): Containers[];
export declare function filterNexployNetworks(networks: Network[]): Network[];
